apiVersion: v1
kind: Service
metadata:
  labels:
    app: products
  name: products
spec:
  ports:
    - name: '7778'
      nodePort: 32222
      port: 7778
      targetPort: 7778
  type: NodePort
  selector:
    app: products
