apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shoppingcart
    version: 'k8s1'
  name: shoppingcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart
      version: 'k8s1'
  template:
    metadata:
      labels:
        app: shoppingcart
        version: 'k8s1'
    spec:
      containers:
        - image: midoblgsm/shopping-cart:dev
          name: shoppingcart
          ports:
            - containerPort: 7778
          imagePullPolicy: Always
          resources:
            requests:
              memory: '50Mi'
              cpu: '100m'
            limits:
              memory: '70Mi'
              cpu: '200m'
